### ISSUE TITLE
Publish to maven repository

### ISSUE THREAD

**Issue by fkrauthan** [jurgc11/yakl#2]
Are there any plans to publish this to the maven repository for easy inclusion in projects?

**Comment by jurgc11** [comment]
I'll try and take a look at that this weekend

**Comment by jurgc11** [comment]
This turns out to be more complicated than I realised. I've just requested the co-ordinates from Sonatype so I can publish to Maven Central, which I think requires some manual work

**Comment by fkrauthan** [comment]
Any news on this by any chance?
